packages:
  - "apps/*"
  - "packages/*"
overrides:
  vite: "^8.0.0"
  effect: ">=3.20.0"
  defu: ">=6.1.5"
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@types/node@26.0.0'
