import type { DesignPersona } from './types';

export const DESIGN_PERSONAS: DesignPersona[] = [
  {
    id: 'minimalist',
    name: 'Dieter',
    avatar: '\u{25CB}',
    philosophy: 'Less, but better. Good design is as little design as possible. Named after Dieter Rams, whose 10 principles of good design shaped modern minimalism.',
    styleKeywords: ['clean', 'whitespace', 'restrained', 'elegant'],
    density: 'spacious',
    colorTemperature: 'cool',
  },
  {
    id: 'bold',
    name: 'Da Vinci',
    avatar: '\u{25C6}',
    philosophy: 'Simplicity is the ultimate sophistication, but boldness captures the soul. Named after Leonardo da Vinci, who merged art and engineering into singular vision.',
    styleKeywords: ['vibrant', 'high-contrast', 'dramatic', 'impactful'],
    density: 'compact',
    colorTemperature: 'warm',
  },
  {
    id: 'accessible',
    name: 'Braille',
    avatar: '\u{267F}',
    philosophy: 'Design for everyone. What is essential must be accessible to all. Named in honor of Louis Braille, who at 15 invented a system that gave millions access to written language.',
    styleKeywords: ['inclusive', 'readable', 'structured', 'clear'],
    density: 'balanced',
    colorTemperature: 'neutral',
  },
  {
    id: 'editorial',
    name: 'Gutenberg',
    avatar: '\u{2726}',
    philosophy: 'Typography is the voice of the page. Let the content breathe and the hierarchy lead. Named after Johannes Gutenberg, whose printing press democratized knowledge.',
    styleKeywords: ['typographic', 'editorial', 'refined', 'literary'],
    density: 'spacious',
    colorTemperature: 'warm',
  },
  {
    id: 'playful',
    name: 'Haring',
    avatar: '\u{273F}',
    philosophy: 'Art is for everybody. Design should bring joy and make people smile. Named after Keith Haring, whose radiant, accessible art turned public spaces into galleries.',
    styleKeywords: ['colorful', 'rounded', 'friendly', 'whimsical'],
    density: 'balanced',
    colorTemperature: 'warm',
  },
  {
    id: 'brutalist',
    name: 'Corbusier',
    avatar: '\u{25A6}',
    philosophy: 'A house is a machine for living in. Raw structure over decoration. Function is beauty. Named after Le Corbusier, father of brutalist architecture.',
    styleKeywords: ['raw', 'structural', 'monospace', 'grid-heavy'],
    density: 'compact',
    colorTemperature: 'cool',
  },
];
